In [ ]:
import torch

torch.manual_seed(0)

# B = 2, vocab_size = 6
probs = torch.tensor(
    [
        [0.10, 0.40, 0.05, 0.30, 0.10, 0.05],  # batch row 0
        [0.20, 0.05, 0.25, 0.10, 0.35, 0.05],  # batch row 1
    ]
)

# Current generated token ids, shape (B, T)
x = torch.tensor(
    [
        [10, 11, 12],
        [20, 21, 22],
    ]
)

print("probs:")
print(probs)
print("probs shape:", probs.shape)

# Use top 3 instead of top 50 for a tiny example
topk_probs, topk_indices = torch.topk(probs, 3, dim=-1)

print("\ntopk_probs:")
print(topk_probs)
print("topk_probs shape:", topk_probs.shape)

print("\ntopk_indices:")
print(topk_indices)
print("topk_indices shape:", topk_indices.shape)

# Pick one position from each row's top-k list
ix = torch.multinomial(topk_probs, 1)

print("\nix sampled from top-k positions:")
print(ix)
print("ix shape:", ix.shape)

# Convert sampled top-k position into actual vocab token id
xcol = torch.gather(topk_indices, -1, ix)

print("\nxcol actual sampled token ids:")
print(xcol)
print("xcol shape:", xcol.shape)

# Append sampled token to each sequence
x_next = torch.cat((x, xcol), dim=1)

print("\nold x:")
print(x)
print("old x shape:", x.shape)

print("\nnew x:")
print(x_next)
print("new x shape:", x_next.shape)

probs:
tensor([[0.1000, 0.4000, 0.0500, 0.3000, 0.1000, 0.0500],
        [0.2000, 0.0500, 0.2500, 0.1000, 0.3500, 0.0500]])
probs shape: torch.Size([2, 6])

topk_probs:
tensor([[0.4000, 0.3000, 0.1000],
        [0.3500, 0.2500, 0.2000]])
topk_probs shape: torch.Size([2, 3])

topk_indices:
tensor([[1, 3, 0],
        [4, 2, 0]])
topk_indices shape: torch.Size([2, 3])

ix sampled from top-k positions:
tensor([[1],
        [1]])
ix shape: torch.Size([2, 1])

xcol actual sampled token ids:
tensor([[3],
        [2]])
xcol shape: torch.Size([2, 1])

old x:
tensor([[10, 11, 12],
        [20, 21, 22]])
old x shape: torch.Size([2, 3])

new x:
tensor([[10, 11, 12,  3],
        [20, 21, 22,  2]])
new x shape: torch.Size([2, 4])
